name: CI for app

on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: run checks
      run: echo " Running checkout code"
           ls -al
           echo "Podemos usar varios commands en un solo run" 