name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: "${{ secrets.MONGO_URI }}"
    MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    DOCKER_USERNAME: "nmosquerar"
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
        
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage:
        needs: unit-testing
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup NodeJS Version
            uses: actions/setup-node@v3
            with:
              node-version: 20

          - name: Set up cache
            uses: actions/cache@v3
            with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  

          - name: run coverage
            run: |
              npm install 
              npm run coverage
            continue-on-error: true

          - name: Archive coverage Result
            uses: actions/upload-artifact@v3
            with:
              name: coverage-Test-Result
              path: coverage-results.xml  

    docker-build:
        needs: code-coverage
        name: Docker Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup NodeJS Version
            uses: actions/setup-node@v3
            with:
              node-version: 20

          - name: login docker
            uses: docker/login-action@v2
            with:
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ env.DOCKER_PASSWORD }}

          - name: Docker Build
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ env.DOCKER_USERNAME }}/solar-system:latest

          - name: Archive Docker Image
            uses: actions/upload-artifact@v3
            with:
              name: Docker-Image
              path: .dockerignore
    